In [ ]:
import tensorflow as tf


In [ ]:
a=tf.constant(3)
print(a)
# 텐서라는 기본 자료형 . 파이썬의 숫자 자료형느낌 
# 그냥 숫자 혹은 리스트 담는곳 끝! 

b=tf.constant([3,4,5])
print(b)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)


텐서가 필요한 이유 

x1*w1+x2*w2 .... 이렇게 여러번 쓰는 건 매우 번거롭다 -> 그래서 행렬을 사용한다 

숫자 여러개를 한꺼번에 계산하기가 좋다!!

- 행렬로 인풋 및 w값 저장가능 
- node값 계산이 쉬워진다 

In [ ]:
텐서 = tf.constant([3,4,5])
텐서2 = tf.constant([6,7,8])
print(텐서 + 텐서2)
# 숫자들을 한꺼번게 계산하기 위해서 tensor를 사용한다 
# tensor는 리스트 형태로 숫자를 집어넣어도 되고 행렬같은 형태로도 가능 



tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [ ]:
ten3 = tf.constant([ [1,2],[3,4] ])
print(ten3)
# 행렬같은 형태 2차원행렬을 사용해서 ! 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
print(tf.add(텐서,텐서2))



tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)



tf.add()
tf.substract()
tf.divide()
tf.multiply()
//tf.matmul() 행렬의 곱셈

In [ ]:
ten4 = tf.zeros([2,2])
print(ten4)
# 0으로 채움 
# shape-> 모양 
# 뒤에서부터 해석하면 됨 2개짜리 데이터가 2개 있음 

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


텐서의 데이터타입 

안에 들어있는 거 알아서 판단해서 변환해줌 int, float 

보통 실수를 많이 넣음 


In [ ]:
ten = tf.constant([3,4,5], tf.float32)
print(ten)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)


In [ ]:
#w = tf.Variable()
w = tf.Variable(1,0)
print(w)
# 딥러닝상의 가중치 weight 
# 형태가 Variable 변경이가능함! 텐서는 변경이 안되네 덧셈 뺄셈은 되는듯 
# Variable 에 값 불러오려면 numpy 쓰면 됨 
print(w.numpy())
w.assign(2) # 실수 넣으니까 에러나네
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
1
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>
